import * as p from '@clack/prompts';
import { isCI, isTTY } from '@clack/prompts';
import pc from 'picocolors';
import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import { HandoverConfigSchema } from '../config/schema.js';
import { DEFAULT_API_KEY_ENV } from '../config/defaults.js';
import {
  detectProviders,
  cheapestDetected,
  patchGitignore,
  computeUpgradeDiff,
  type DetectedProvider,
  type UpgradeDiff,
} from './init-detectors.js';
import { detectMonorepo } from './monorepo.js';

// Locked by CONTEXT.md D-10 + STATE.md pending todo. Do NOT use blanket '.handover/'.
const GITIGNORE_ENTRIES = ['.handover/cache', '.handover/telemetry.db'];

const PROVIDER_OPTIONS = [
  { value: 'anthropic', label: 'Anthropic', hint: 'Claude Opus — recommended' },
  { value: 'openai', label: 'OpenAI', hint: 'GPT-4o' },
  { value: 'ollama', label: 'Ollama', hint: 'Local models — zero external data transfer' },
  { value: 'gemini', label: 'Google Gemini', hint: 'Gemini 2.5 Flash — generous free tier' },
] as const;

interface RunInitOptions {
  yes?: boolean;
  upgrade?: boolean;
}

/**
 * Interactive init flow using @clack/prompts.
 * Creates .handover.yml with polished UX (CONTEXT.md: "feel like create-next-app").
 *
 * Composes Plan 02 helpers (detectProviders, cheapestDetected, patchGitignore,
 * computeUpgradeDiff) and Plan 03's detectMonorepo into the runInit user-facing
 * flow. Trust boundary entry point — passes only safe values into helpers.
 */
export async function runInit(options: RunInitOptions = {}): Promise<void> {
  const isInteractive = isTTY(process.stdout) && !isCI();

  if (!isInteractive && !options.yes) {
    process.stderr.write(
      'handover init: non-interactive environment detected.\n' +
        'Run with --yes to create a default configuration file non-interactively.\n',
    );
    process.exitCode = 1;
    return;
  }

  // ── --upgrade branch (CONTEXT.md D-14 through D-19) ────────────────────────
  // Primary control: hand off to runUpgrade BEFORE the fresh-init early-exit guard
  // so `--upgrade --yes` never falls through to the "already exists - skipping" path.
  if (options.upgrade) {
    await runUpgrade(options, isInteractive);
    return;
  }

  // ── Fresh-init early exit (CONTEXT.md D-04 / Open Q2 — guard updated) ──────
  // Defense-in-depth: even though runUpgrade handles --upgrade above, we keep the
  // explicit `&& !options.upgrade` clause here so any future refactor that calls
  // runInit({ yes: true, upgrade: true }) without taking the runUpgrade branch
  // still does not hit the skip-early-exit. Path uses join(process.cwd(), ...) so
  // vi.spyOn(process, 'cwd') in tests redirects to the memfs virtual cwd.
  if (existsSync(join(process.cwd(), '.handover.yml')) && options.yes && !options.upgrade) {
    process.stdout.write('.handover.yml already exists - skipping.\n');
    return;
  }

  // Run detectors up front; cheap and useful in both --yes and interactive paths.
  const detected = await detectProviders();

  if (options.yes) {
    await runYesMode(detected);
    return;
  }

  await runInteractive(detected);
}

// ─── Yes-mode (--yes, no upgrade) ────────────────────────────────────────────

async function runYesMode(detected: DetectedProvider[]): Promise<void> {
  // D-02 + D-04: cheapest detected wins; fallback to 'anthropic' if zero detected
  const provider = cheapestDetected(detected) ?? 'anthropic';
  const top = detected[0];

  const config: Record<string, unknown> = { provider };
  // D-05: Codex subscription → record authMethod alongside provider: 'openai'
  if (top?.provider === 'openai' && top.source === 'codex-subscription') {
    config.authMethod = 'subscription';
  }

  // Validate (best-effort — drops unknown keys; we only set provider [+ authMethod])
  HandoverConfigSchema.parse(config);

  const yamlContent = [
    '# handover configuration',
    '# Generated by `handover init --yes`',
    `# Docs: https://github.com/handover/handover`,
    '',
    stringifyYaml(config, { lineWidth: 80 }),
  ].join('\n');

  writeFileSync(join(process.cwd(), '.handover.yml'), yamlContent, 'utf-8');
  patchGitignore(process.cwd(), GITIGNORE_ENTRIES);

  const note =
    detected.length > 0
      ? ` (provider: ${provider} — cheapest detected)`
      : ' (provider: anthropic — no env vars detected, backward-compatible default)';
  process.stdout.write(`Created .handover.yml${note}.\n`);
  process.stdout.write('Run handover generate to analyze your codebase.\n');
}

// ─── Interactive mode (full wizard) ──────────────────────────────────────────

async function runInteractive(detected: DetectedProvider[]): Promise<void> {
  p.intro(pc.bgCyan(pc.black(' handover init ')));

  // Existing-config overwrite confirm
  if (existsSync(join(process.cwd(), '.handover.yml'))) {
    const overwrite = await p.confirm({
      message: '.handover.yml already exists. Overwrite?',
      initialValue: false,
    });
    if (p.isCancel(overwrite) || !overwrite) {
      p.cancel('Keeping existing config.');
      return;
    }
  }

  // D-07: monorepo info line (display-only, no per-package picker)
  const mono = detectMonorepo(process.cwd());
  if (mono.isMonorepo) {
    p.note(
      `Detected ${pc.cyan(mono.tool ?? 'monorepo')} workspace (root: ${pc.dim(mono.workspaceRoot ?? '.')}). Analysis scope: current directory.`,
      'Monorepo',
    );
  }

  // D-03: show ALL providers, suffix detected ones, pre-select cheapest
  const detectedSet = new Set(detected.map((d) => d.provider));
  const cheapest = cheapestDetected(detected);

  const answers = await p.group(
    {
      provider: () =>
        p.select({
          message: 'Which LLM provider?',
          initialValue: cheapest ?? 'anthropic',
          options: PROVIDER_OPTIONS.map((opt) => ({
            ...opt,
            label: detectedSet.has(opt.value) ? `${opt.label} (detected)` : opt.label,
          })),
        }),
      apiKeyEnv: ({ results }) => {
        if (results.provider === 'ollama') {
          return Promise.resolve('');
        }
        const defaultEnv = DEFAULT_API_KEY_ENV[results.provider as string] ?? 'LLM_API_KEY';
        return p.text({
          message: 'Environment variable for API key:',
          initialValue: defaultEnv,
          validate: (v) => {
            if (!v && results.provider !== 'ollama') return 'Required for cloud providers';
          },
        });
      },
    },
    {
      onCancel: () => {
        p.cancel('Setup cancelled.');
        process.exit(0);
      },
    },
  );

  const s = p.spinner();
  s.start('Detecting project...');
  const projectInfo = detectProject();
  s.stop(`Detected: ${pc.cyan(projectInfo.name)} (${projectInfo.language})`);

  const config: Record<string, unknown> = { provider: answers.provider };
  const defaultEnv = DEFAULT_API_KEY_ENV[answers.provider] ?? '';
  if (answers.apiKeyEnv && answers.apiKeyEnv !== defaultEnv) {
    config.apiKeyEnv = answers.apiKeyEnv;
  }
  if (projectInfo.name) {
    config.project = { name: projectInfo.name };
  }
  // D-05: Codex auto-detected in interactive mode too (only if user picked openai AND Codex was the top source)
  const top = detected[0];
  if (
    answers.provider === 'openai' &&
    top?.provider === 'openai' &&
    top.source === 'codex-subscription'
  ) {
    config.authMethod = 'subscription';
  }

  const validated = HandoverConfigSchema.parse(config);

  // D-08: monorepo header comment in generated YAML
  const monoComment = mono.isMonorepo
    ? `# detected: ${mono.tool} monorepo, analyzing from ${process.cwd()}`
    : null;

  const yamlContent = [
    '# handover configuration',
    '# Generated by `handover init`',
    `# Docs: https://github.com/handover/handover`,
    ...(monoComment ? [monoComment] : []),
    '',
    stringifyYaml(config, { lineWidth: 80 }),
  ].join('\n');

  writeFileSync(join(process.cwd(), '.handover.yml'), yamlContent, 'utf-8');
  patchGitignore(process.cwd(), GITIGNORE_ENTRIES);

  // D-05 display: Codex subscription shows in summary
  const providerLabel =
    config.authMethod === 'subscription'
      ? `${validated.provider} (Codex subscription)`
      : validated.provider;

  p.note(
    [
      `${pc.dim('Provider:')} ${pc.cyan(providerLabel)}`,
      `${pc.dim('Model:')}    ${pc.cyan(validated.model ?? 'default')}`,
      `${pc.dim('Output:')}   ${pc.cyan(validated.output)}`,
      `${pc.dim('Config:')}   ${pc.cyan('.handover.yml')}`,
    ].join('\n'),
    'Configuration',
  );

  p.outro(`Run ${pc.cyan('handover generate')} to analyze your codebase`);
}

// ─── Upgrade mode (--upgrade) ────────────────────────────────────────────────

async function runUpgrade(options: RunInitOptions, isInteractive: boolean): Promise<void> {
  const configPath = join(process.cwd(), '.handover.yml');
  if (!existsSync(configPath)) {
    process.stdout.write('No .handover.yml found — run `handover init` to create one.\n');
    process.exitCode = 1;
    return;
  }

  const existing = readFileSync(configPath, 'utf-8');
  const diffs = computeUpgradeDiff(existing);

  const customized = diffs.filter((d) => d.action === 'customized');
  const atDefault = diffs.filter((d) => d.action === 'at-default');
  const missing = diffs.filter((d) => d.action === 'missing');
  const unknown = diffs.filter((d) => d.action === 'unknown');

  // Build the merged object (customized + at-default preserved; missing → default; unknown → kept verbatim).
  const merged: Record<string, unknown> = {};
  for (const d of diffs) {
    if (d.action === 'missing') {
      merged[d.key] = d.defaultValue;
    } else {
      merged[d.key] = d.currentValue;
    }
  }

  // D-19: report unknown keys verbosely so users can clean up stale config
  for (const u of unknown) {
    process.stdout.write(
      `Found unknown key '${u.key}' — leaving as-is. Remove manually if no longer needed.\n`,
    );
  }

  // D-17: --yes --upgrade is deterministic — one-liner summary, no confirm prompt
  if (options.yes || !isInteractive) {
    writeUpgradedYaml(merged);
    process.stdout.write(
      `Upgraded .handover.yml — preserved ${customized.length} customized fields, refreshed ${atDefault.length} defaults, added ${missing.length} new keys.\n`,
    );
    return;
  }

  // D-16: interactive 3-column table + confirm
  p.intro(pc.bgCyan(pc.black(' handover init --upgrade ')));

  if (diffs.length === 0) {
    p.outro('.handover.yml is already up to date.');
    return;
  }

  const tableRows = diffs.map((d) => formatUpgradeRow(d));
  p.note(
    [
      pc.dim('key                            current                          action'),
      pc.dim('────────────────────────────────────────────────────────────────────────────'),
      ...tableRows,
    ].join('\n'),
    'Upgrade preview',
  );
  p.note(
    'Note: handover init --upgrade does not preserve inline comments. Back up your .handover.yml first if needed.',
    'Heads up',
  );

  const apply = await p.confirm({ message: 'Apply these changes?', initialValue: true });
  if (p.isCancel(apply) || !apply) {
    p.cancel('Upgrade cancelled — .handover.yml unchanged.');
    return;
  }

  writeUpgradedYaml(merged);
  p.outro(
    `Upgraded: preserved ${customized.length} customized, refreshed ${atDefault.length} defaults, added ${missing.length} new keys.`,
  );
}

function formatUpgradeRow(d: UpgradeDiff): string {
  const key = d.key.padEnd(30).slice(0, 30);
  const currentStr =
    d.action === 'missing'
      ? pc.dim('(missing)')
      : truncate(JSON.stringify(d.currentValue) ?? '', 32);
  const actionLabel = (
    {
      customized: pc.cyan('preserve (customized)'),
      'at-default': pc.dim('refresh (was default)'),
      missing: pc.green('add (new key)'),
      unknown: pc.yellow('preserve (unknown)'),
    } as const
  )[d.action];
  return `${key} ${currentStr.padEnd(32)} ${actionLabel}`;
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1) + '…' : s.padEnd(n);
}

function writeUpgradedYaml(merged: Record<string, unknown>): void {
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const yamlContent = [
    '# handover configuration',
    `# Updated by handover init --upgrade ${today}`,
    '# Note: --upgrade does not preserve inline YAML comments. Back up before re-running if needed.',
    '',
    stringifyYaml(merged, { lineWidth: 80 }),
  ].join('\n');
  writeFileSync(join(process.cwd(), '.handover.yml'), yamlContent, 'utf-8');
}

// ─── Local helper kept from original init.ts ─────────────────────────────────

function detectProject(): { name: string; language: string } {
  let name = 'project';
  let language = 'unknown';

  if (existsSync(join(process.cwd(), 'package.json'))) {
    try {
      const pkg = JSON.parse(readFileSync(join(process.cwd(), 'package.json'), 'utf-8'));
      name = pkg.name ?? name;
      language = 'typescript';
    } catch {
      // Ignore parse errors — treat as if no info
    }
  }

  if (language === 'unknown') {
    if (existsSync(join(process.cwd(), 'tsconfig.json'))) language = 'typescript';
    else if (
      existsSync(join(process.cwd(), 'pyproject.toml')) ||
      existsSync(join(process.cwd(), 'setup.py'))
    )
      language = 'python';
    else if (existsSync(join(process.cwd(), 'Cargo.toml'))) language = 'rust';
    else if (existsSync(join(process.cwd(), 'go.mod'))) language = 'go';
    else if (existsSync(join(process.cwd(), 'package.json'))) language = 'javascript';
  }

  if (name === 'project') {
    name = process.cwd().split('/').pop() ?? 'project';
  }

  return { name, language };
}
