import * as p from '@clack/prompts';
import pc from 'picocolors';
import { existsSync, writeFileSync } from 'node:fs';
import { stringify as stringifyYaml } from 'yaml';
import { pkceLogin } from '../auth/pkce-login.js';
import { TokenStore } from '../auth/token-store.js';
import { HandoverConfigSchema } from '../config/schema.js';

const FIRST_RUN_ENV_VARS = [
  'ANTHROPIC_API_KEY',
  'OPENAI_API_KEY',
  'GEMINI_API_KEY',
  'GOOGLE_API_KEY',
  'GROQ_API_KEY',
  'DEEPSEEK_API_KEY',
] as const;

const PROVIDER_API_KEY_ENV = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
} as const;

type OnboardingProvider = 'anthropic' | 'openai' | 'openai-subscription' | 'gemini' | 'ollama';

function hasConfiguredProviderEnv(): boolean {
  return FIRST_RUN_ENV_VARS.some((name) => (process.env[name] ?? '').trim().length > 0);
}

export function isFirstRun(): boolean {
  return !existsSync('.handover.yml') && !hasConfiguredProviderEnv();
}

export async function runOnboarding(): Promise<boolean> {
  p.intro(pc.bgCyan(pc.black(' handover setup ')));

  const selected = await p.select({
    message: 'Choose a provider to get started:',
    options: [
      {
        value: 'anthropic',
        label: 'Anthropic (Claude)',
        hint: 'Requires ANTHROPIC_API_KEY',
      },
      {
        value: 'openai',
        label: 'OpenAI (GPT-4o)',
        hint: 'Requires OPENAI_API_KEY',
      },
      {
        value: 'openai-subscription',
        label: 'OpenAI Codex subscription',
        hint: 'Browser login',
      },
      {
        value: 'gemini',
        label: 'Google Gemini',
        hint: 'Requires GEMINI_API_KEY',
      },
      {
        value: 'ollama',
        label: 'Ollama (local)',
        hint: 'No API key needed',
      },
    ],
  });

  if (p.isCancel(selected)) {
    p.cancel('Setup cancelled.');
    return false;
  }

  const providerChoice = selected as OnboardingProvider;
  const provider = providerChoice === 'openai-subscription' ? 'openai' : providerChoice;
  const authMethod = providerChoice === 'openai-subscription' ? 'subscription' : 'api-key';

  const config = {
    provider,
    authMethod,
  };

  HandoverConfigSchema.parse(config);

  const yamlContent = [
    '# handover configuration',
    '# Generated by onboarding in `handover generate`',
    '# Docs: https://github.com/handover/handover',
    '',
    stringifyYaml(config, { lineWidth: 80 }),
  ].join('\n');

  writeFileSync('.handover.yml', yamlContent, 'utf-8');
  p.log.success(`Created ${pc.cyan('.handover.yml')}`);

  if (providerChoice === 'openai-subscription') {
    await pkceLogin('openai', new TokenStore());
    p.log.success('Authenticated with OpenAI subscription');
    p.outro(`Continuing with ${pc.cyan('handover generate')}...`);
    return true;
  }

  if (providerChoice === 'ollama') {
    p.outro(`Setup complete. Continuing with ${pc.cyan('handover generate')}...`);
    return true;
  }

  const envVarName = PROVIDER_API_KEY_ENV[providerChoice as keyof typeof PROVIDER_API_KEY_ENV];
  p.note(
    [
      `Export your API key first:`,
      '',
      `${pc.cyan(`export ${envVarName}=your-api-key-here`)}`,
      '',
      `Then run ${pc.cyan('handover generate')} again.`,
    ].join('\n'),
    'API key required',
  );
  p.outro('Setup complete. Waiting for API key export.');
  return false;
}
