name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How do you trigger this bug?
      placeholder: "1. Run `npx handover-cli generate`\n2. ...\n3. See error"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: handover-cli Version
      placeholder: "e.g. 0.1.0 (run `npx handover-cli --version`)"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      placeholder: "e.g. 20.10.0 (run `node --version`)"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots (optional)
      description: Paste any error output or attach screenshots
      render: shell
  - type: checkboxes
    id: existing-issues
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
